tunnel: b35132c3-7770-4baf-90a9-910958da6928
credentials-file: C:\Users\romil\.cloudflared\b35132c3-7770-4baf-90a9-910958da6928.json

ingress:
  - hostname: ewatts.uk
    service: http://localhost:3000
  - hostname: api.ewatts.uk
    service: http://localhost:8080
  - service: http_status:404
